### ISSUE TITLE
how to config seq via logging config file?

### ISSUE THREAD

**Issue by constructor-igor** [tintoy/seqlog#3]
Hi,

could you add sample how can be configured python seqlog via logging config file?

thank you,
Igor.

**Comment by tintoy** [comment]
Hi. 

It's been a while since I looked at this project, so bear with me - I'll look into it shortly :)

**Comment by tintoy** [comment]
Hmm, sorry, I don't think `seqlog` supports configuration from a config file yet (but I can add support for it).

I'm about to head off on holiday but I'll get this done as soon as I can!

**Comment by tintoy** [comment]
@constructor-igor I'm not at my dev machine at the moment, but would you mind giving this a try and letting me know if it works for you? If so, I'll update the docs to match:

`logging-config.yml`:

```yaml
# Configure logging from scratch.
disable_existing_loggers: True

# Configure the root logger to use Seq
root:
  class: seqlog.structured_logging.StructuredLogger
  level: INFO
  handlers:
    - seq

handlers:
  seq:
    class: seqlog.structured_logging.SeqLogHandler
    formatter: seq

    # Seq-specific settings.
    server_url: 'http://localhost:5341/'
    api_key: 'MyApiKey'

formatters:
  seq:
    style: '{'
```

`app.py`:

```python
from logging.config import dictConfig
import yaml

with open('./logging-config.yml') as logging_config_file:
  logging_config = yaml.load(logging_config_file)

dictConfig(logging_config)
```

**Comment by tintoy** [comment]
Note that if you also want to log to console, you can add a second handler using the `seqlog.structured_logging.ConsoleStructuredLogHandler` class.

**Comment by constructor-igor** [comment]
my test fails on line
```
dictConfig(logging_config)
```
with message  ```ValueError: dictionary doesn't specify a version```

**Comment by tintoy** [comment]
Hmm, ok - give me a minute...

**Comment by tintoy** [comment]
Try this `logging-config.yml`:

```yaml
version: 1

# Configure logging from scratch.
disable_existing_loggers: True

# Configure the root logger to use Seq
root:
  class: seqlog.structured_logging.StructuredLogger
  level: INFO
  handlers:
    - seq

handlers:
  seq:
    class: seqlog.structured_logging.SeqLogHandler
    formatter: seq

    # Seq-specific settings (add any others you need, they're just kwargs for SeqLogHandler's constructor).
    server_url: 'http://localhost:5341/'
    api_key: 'MyApiKey'

formatters:
  seq:
    style: '{'
```

_Or_, try changing the code to:

```python
from logging.config import dictConfig
import yaml

with open('./logging-config.yml') as logging_config_file:
  logging_config = yaml.load(logging_config_file)

logging_config['version'] = 1

dictConfig(logging_config)
```

**Comment by tintoy** [comment]
(sorry, forgot that the `version` key is required for forward compatibility)

**Comment by constructor-igor** [comment]
working sample:
```python
    def __init__(self, services=None, logger=None):
        self.logger = logger
        if self.logger is None:
            log_config_file = 'logging.conf'
            if os.path.exists(log_config_file):
                logging.config.fileConfig(log_config_file)
            else:
                logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)-5s [MyApi].[%(funcName)s] %(message)s')
            self.logger = logging.getLogger("root")
        self.logger.info("created MyApi {0} on computer {1}".format(__version__, os.environ["COMPUTERNAME"]))

        import seqlog
        seq_handler = seqlog.log_to_seq(
            server_url="http://<address>:5341",
            api_key="",
            level=logging.INFO,
            batch_size=1,
            auto_flush_timeout=10000,  # milliseconds
            override_root_logger=True,
        )
        self.logger.addHandler(seq_handler)
        self.logger.info("created MyApi {0} on computer {1}".format(__version__, os.environ["COMPUTERNAME"]))

```

**Comment by constructor-igor** [comment]
not working sample (no errors, but web UI doesn't show nothing):
```python
def __init__(self, services=None, logger=None):
        self.logger = logger
        if self.logger is None:
            log_config_file = 'logging.conf'
            if os.path.exists(log_config_file):
                logging.config.fileConfig(log_config_file)
            else:
                logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)-5s [MyApi].[%(funcName)s] %(message)s')
            self.logger = logging.getLogger("root")
        self.logger.info("created MyApi {0} on computer {1}".format(__version__, os.environ["COMPUTERNAME"]))

        from logging.config import dictConfig
        import yaml

        with open('./logging-config.yml') as logging_config_file:
            logging_config = yaml.load(logging_config_file)
        dictConfig(logging_config)
        seq_logger = logging.getLogger("")
        seq_logger.info("created seq")

```

file logging-config.yml
```
# This is the Python logging schema version (currently, only the value 1 is supported here).
version: 1

# Configure logging from scratch.
disable_existing_loggers: True

# Configure the root logger to use Seq
root:
  class: seqlog.structured_logging.StructuredLogger
  level: INFO
  handlers:
    - seq

handlers:
  seq:
    class: seqlog.structured_logging.SeqLogHandler
    formatter: seq

    # Seq-specific settings (add any others you need, they're just kwargs for SeqLogHandler's constructor).
    server_url: 'http://<address>:5341'
    api_key: ''

formatters:
  seq:
    style: '{'
```

**Comment by tintoy** [comment]
Interesting. What happens if you replace `getLogger('')` with `getLogger()`?

**Comment by tintoy** [comment]
(i think one passes `None` rather than  `''` to get at the root logger)

**Comment by tintoy** [comment]
Looking at what Python's `logging.config` supports, I think I'll need to write a bit of glue code to make this work properly. I'll let you know as soon as I've built a decent configuration story for this; unfortunately I won't be back home until early January so for now you may need to fake something up. Sorry about that but it's hard to code on a phone :)

**Comment by tintoy** [comment]
Will need a custom [DictConfigurator](https://docs.python.org/3/library/logging.config.html) at least.

**Comment by constructor-igor** [comment]
![image](https://user-images.githubusercontent.com/1849690/34339246-454770ba-e97a-11e7-9853-0b780355cc35.png)

if it can help, I'll publish 2 samples

**Comment by tintoy** [comment]
Thanks, that would be great! If you can open a PR for the docs I can easily merge that from my phone :)

**Comment by tintoy** [comment]
And I'll see if I can borrow a laptop for a couple of hours tomorrow - might be able to build a simple configurator to get you going for now.

**Comment by constructor-igor** [comment]
When I prepared simple samples, the problematic test **sometimes** started to work.

**Comment by tintoy** [comment]
Just woke up - will have a coffee or 2 and see if I can get hold of a laptop; we'll work this out one way or the other :)

**Comment by tintoy** [comment]
Ok, I managed to try this out for myself. The following config works:

```yml
# This is the Python logging schema version (currently, only the value 1 is supported here).
version: 1

# Configure logging from scratch.
disable_existing_loggers: True

# Configure the root logger to use Seq
root:
  class: seqlog.structured_logging.StructuredRootLogger
  level: INFO
  handlers:
    - seq
    - console

loggers:
  diddly:
    class: seqlog.structured_logging.StructuredLogger
    propagate: False
    level: INFO
    handlers:
      - seq
      - console

handlers:
  console:
    class: seqlog.structured_logging.ConsoleStructuredLogHandler
    formatter: seq

  seq:
    class: seqlog.structured_logging.SeqLogHandler
    formatter: seq

    # Seq-specific settings (add any others you need, they're just kwargs for SeqLogHandler's constructor).
    server_url: 'http://localhost:5341'
    api_key: 'TSvDYRTsdGg3wFqMP0w4'

formatters:
  seq:
    style: '{'
```

```python
import logging
import yaml

with open('./logging-config.yml') as logging_config_file:
    logging_config = yaml.load(logging_config_file)

logging.config.dictConfig(logging_config)

root_logger = logging.getLogger()
root_logger.info('This is the root logger.')

diddly_logger = logging.getLogger('diddly')
diddly_logger.info('This is the diddly logger.')
```

**Comment by tintoy** [comment]
Would you mind trying that and seeing if it works for you?

**Comment by constructor-igor** [comment]
I am going to try now

**Comment by constructor-igor** [comment]
The sample works (only, it's necessary to add ```import logging.config```).
also I added file handler:
```
  # Log to file
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: seq
    filename: info.log
    maxBytes: 1048576 # 1MB
    backupCount: 10
    encoding: utf8
```

Thank you!


I am going to check on developing project.

**Comment by tintoy** [comment]
Great! Are you still going to do a PR for the docs or would you like me to do it? Either is fine with me :)

**Comment by constructor-igor** [comment]
Original configuration doesn't work for developing project and remote server.
Only when I added ```batch_size: 1``` and ```auto_flush_timeout: 10000``` from code sample it started to work.
```
  # Log to Seq
  seq:
    class: seqlog.structured_logging.SeqLogHandler
    formatter: simple
    # Seq-specific settings (add any others you need, they're just kwargs for SeqLogHandler's constructor).
    server_url: http://<address>:5341
    api_key: ''
    batch_size: 1
    auto_flush_timeout: 10000
```
